# Generated by Django 4.2.5 on 2023-10-16 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("furrysongs", "0002_rating_nick_alter_rating_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="jezyk",
            field=models.CharField(default="Brak", max_length=30),
        ),
        migrations.AlterField(
            model_name="rating",
            name="nick",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="rating",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="furrysongs.song",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="title",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
